### ISSUE TITLE
docker bug

### ISSUE THREAD

**Issue by 46fafa** [A164759920/I_Goto_Library#2]
使用docker拉取镜像时卡在 => [vue 5/7] RUN npm install一直加载不出来
![image](https://github.com/A164759920/I_Goto_Library/assets/92380602/8858590e-c217-410f-be6c-ee7c50e81ce6)

**Comment by A164759920** [comment]
> [<img alt="@A164759920" width="40" height="40" src="https://avatars.githubusercontent.com/u/109188195?s=80&amp;v=4">](/A164759920)
> 
> 
> #### Add a comment

我之前在本地虚拟机里安装的时候也有这个情况，**可能是因为最近taobao的npm库搬家了**，导致原来 **许多使用taobao作为镜像源的npm库** 下载失败了，可以尝试先将Vue下的Dockerfile里

`RUN npm config set registry https://registry.npm.taobao.org`
替换为：
`npm config set registry https : //registry.npmmirror.com`
这个多半就是某个包的地址访问不到卡住了，我之前在本地拉的时候也是时好时坏的，有能力的话可以手动部署Vue的页面

**Comment by A164759920** [comment]
🤔删除**package.lock.json + 重新配置npm源** 好像也不太行
![image](https://github.com/A164759920/I_Goto_Library/assets/109188195/6b39ddb2-c5bb-4b07-b76d-85fc2191f3d0)
安装时它似乎卡在了这个地方，后续有空 我看看是不是这个版本的node和npm的不匹配的bug
但是测试直接在虚拟机中 npm install 是可以成功的，很奇怪。
我推荐你直接在机器上安装npm并且手动 
`1.删除package.lock.json`
`2. npm install` 
`3.npm run serve` 
`来调试前端页面，过程中有任何问题都可以联系我
