### ISSUE TITLE
返回值为True，但实际微信没定到位置

### ISSUE THREAD

**Issue by Jonah4fun** [A164759920/I_Goto_Library#3]
如题

**Comment by A164759920** [comment]
@Jonah4fun 
我在以前开发的时候就遇到过这个问题，**只要是正常提交预约返回值都是True**，但是**【实际位置是否预定成功】**要取决于服务器websocket连接给你返回的消息为准。你有自己修改过程序吗？ 我自用时应该已经对这部分逻辑进行过处理了，你不能第一次返回True就关闭程序，而是要等到websocket返回预订成功的消息后由程序自行关闭。

这是我服务器昨晚上的log，目前还能正常使用
![image](https://github.com/A164759920/I_Goto_Library/assets/109188195/9d04c721-6d84-458a-9fe8-0b11b0feca11)
